In [15]:
import pandas as pd

In [16]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)

In [4]:
df = pd.read_excel("a4wdi.xlsx")

In [5]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.914625,17.392349,17.892005,18.359993,18.795151,19.295176,19.788156,20.279599,20.773627,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.473301,6.720331,7.015917,7.281390,7.513673,7.809566,8.075889,8.366010,8.684137,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,37.870347,38.184152,38.543180,38.801719,39.039014,39.323186,39.643848,39.894830,40.213891,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.695183,31.859257,33.903515,38.851444,40.197332,43.028332,44.389773,46.268621,48.103609,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.672306,17.623956,16.516633,24.594474,25.389297,27.041743,29.138285,30.998687,32.772690,NaN

In [6]:
df.describe

<bound method NDFrame.describe of                        Country Name Country Code  \
0       Africa Eastern and Southern          AFE
1       Africa Eastern and Southern          AFE
2       Africa Eastern and Southern          AFE
3       Africa Eastern and Southern          AFE
4       Africa Eastern and Southern          AFE
...                             ...          ...
392877                     Zimbabwe          ZWE
392878                     Zimbabwe          ZWE
392879                     Zimbabwe          ZWE
392880                     Zimbabwe          ZWE
392881                     Zimbabwe          ZWE

                                           Indicator Name     Indicator Code  \
0       Access to clean fuels and technologies for coo...     EG.CFT.ACCS.ZS
1       Access to clean fuels and technologies for coo...  EG.CFT.ACCS.RU.ZS
2       Access to clean fuels and technologies for coo...  EG.CFT.ACCS.UR.ZS
3                 Access to electricity (% of population)     EG.ELC.ACCS.ZS
4       Access to electricity, rural (% of rural popul...  EG.ELC.ACCS.RU.ZS
...                                                   ...                ...
392877  Women who believe a husband is justified in be...     SG.VAW.REFU.ZS
392878  Women who were first married by age 15 (% of w...  SP.M15.2024.FE.ZS
392879  Women who were first married by age 18 (% of w...  SP.M18.2024.FE.ZS
392880  Women's share of population ages 15+ living wi...  SH.DYN.AIDS.FE.ZS
392881  Young people (ages 15-24) newly infected with HIV     SH.HIV.INCD.YG

        1960  1961  1962  1963  1964  1965  ...          2013          2014  \
0        NaN   NaN   NaN   NaN   NaN   NaN  ...     16.914625     17.392349
1        NaN   NaN   NaN   NaN   NaN   NaN  ...      6.473301      6.720331
2        NaN   NaN   NaN   NaN   NaN   NaN  ...     37.870347     38.184152
3        NaN   NaN   NaN   NaN   NaN   NaN  ...     31.695183     31.859257
4        NaN   NaN   NaN   NaN   NaN   NaN  ...     18.672306     17.623956
...      ...   ...   ...   ...   ...   ...  ...           ...           ...
392877   NaN   NaN   NaN   NaN   NaN   NaN  ...           NaN           NaN
392878   NaN   NaN   NaN   NaN   NaN   NaN  ...           NaN           NaN
392879   NaN   NaN   NaN   NaN   NaN   NaN  ...           NaN           NaN
392880   NaN   NaN   NaN   NaN   NaN   NaN  ...     59.100000     59.400000
392881   NaN   NaN   NaN   NaN   NaN   NaN  ...  20000.000000  19000.000000

                2015          2016          2017          2018         2019  \
0          17.892005     18.359993     18.795151     19.295176    19.788156
1           7.015917      7.281390      7.513673      7.809566     8.075889
2          38.543180     38.801719     39.039014     39.323186    39.643848
3          33.903515     38.851444     40.197332     43.028332    44.389773
4          16.516633     24.594474     25.389297     27.041743    29.138285
...              ...           ...           ...           ...          ...
392877     14.500000           NaN           NaN           NaN          NaN
392878      3.700000           NaN           NaN           NaN     5.400000
392879     32.400000           NaN           NaN           NaN    33.700000
392880     59.500000     59.700000     59.900000     60.100000    60.300000
392881  17000.000000  15000.000000  13000.000000  10000.000000  8600.000000

               2020         2021  2022
0         20.279599    20.773627   NaN
1          8.366010     8.684137   NaN
2         39.894830    40.213891   NaN
3         46.268621    48.103609   NaN
4         30.998687    32.772690   NaN
...             ...          ...   ...
392877          NaN          NaN   NaN
392878          NaN          NaN   NaN
392879          NaN          NaN   NaN
392880    60.500000    60.700000   NaN
392881  7700.000000  6800.000000   NaN

[392882 rows x 67 columns]>

In [7]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],
      dtype='object')

In [14]:
print(df['Indicator Name'].unique())

['Access to clean fuels and technologies for cooking (% of population)'
 'Access to clean fuels and technologies for cooking, rural (% of rural population)'
 'Access to clean fuels and technologies for cooking, urban (% of urban population)'
 'Access to electricity (% of population)'
 'Access to electricity, rural (% of rural population)'
 'Access to electricity, urban (% of urban population)'
 'Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+)'
 'Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)'
 'Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)'
 'Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)'
 'Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)'
 'Account ownership at a financial institution or with a mobile-money-service provider, primary education or less (% of population ages 15+)'
 'Account ownership at a financial institution or with a mobile-money-service provider, richest 60% (% of population ages 15+)'
 'Account ownership at a financial institution or with a mobile-money-service provider, secondary education or more (% of population ages 15+)'
 'Account ownership at a financial institution or with a mobile-money-service provider, young adults (% of population ages 15-24)'
 'Adequacy of social insurance programs (% of total welfare of beneficiary households)'
 'Adequacy of social protection and labor programs (% of total welfare of beneficiary households)'
 'Adequacy of social safety net programs (% of total welfare of beneficiary households)'
 'Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households)'
 'Adjusted net enrollment rate, primary (% of primary school age children)'
 'Adjusted net enrollment rate, primary, female (% of primary school age children)'
 'Adjusted net enrollment rate, primary, male (% of primary school age children)'
 'Adjusted net national income (annual % growth)'
 'Adjusted net national income (constant 2015 US$)'
 'Adjusted net national income (current US$)'
 'Adjusted net national income per capita (annual % growth)'
 'Adjusted net national income per capita (constant 2015 US$)'
 'Adjusted net national income per capita (current US$)'
 'Adjusted net savings, excluding particulate emission damage (% of GNI)'
 'Adjusted net savings, excluding particulate emission damage (current US$)'
 'Adjusted net savings, including particulate emission damage (% of GNI)'
 'Adjusted net savings, including particulate emission damage (current US$)'
 'Adjusted savings: carbon dioxide damage (% of GNI)'
 'Adjusted savings: carbon dioxide damage (current US$)'
 'Adjusted savings: consumption of fixed capital (% of GNI)'
 'Adjusted savings: consumption of fixed capital (current US$)'
 'Adjusted savings: education expenditure (% of GNI)'
 'Adjusted savings: education expenditure (current US$)'
 'Adjusted savings: energy depletion (% of GNI)'
 'Adjusted savings: energy depletion (current US$)'
 'Adjusted savings: gross savings (% of GNI)'
 'Adjusted savings: mineral depletion (% of GNI)'
 'Adjusted savings: mineral depletion (current US$)'
 'Adjusted savings: natural resources depletion (% of GNI)'
 'Adjusted savings: net forest depletion (% of GNI)'
 'Adjusted savings: net forest depletion (current US$)'
 'Adjusted savings: net national savings (% of GNI)'
 'Adjusted savings: net national savings (current US$)'
 'Adjusted savings: particulate emission damage (% of GNI)'
 'Adjusted savings: particulate emission damage (current US$)'
 'Adolescent fertility rate (births per 1,000 women ages 15-19)'
 'Adolescents out of school (% of lower secondary school age)'
 'Adolescents out of school, female (% of female lower secondary school age)'
 'Adolescents out of school, male (% of male lower secondary school age)'
 'Adults (ages 15+) and children (ages 0-14) newly infected with HIV'
 'Adults (ages 15-49) newly infected with HIV'
 'Age dependency ratio (% of working-age population)'
 'Age dependency ratio, old (% of working-age population)'
 'Age dependency ratio, young (% of working-age population)'
 'Agricultural irrigated land (% of total agricultural land)'
 'Agricultural land (% of land area)' 'Agricultural land (sq. km)'
 'Agricultural machinery, tractors'
 'Agricultural machinery, tractors per 100 sq. km of arable land'
 'Agricultural methane emissions (% of total)'
 'Agricultural methane emissions (thousand metric tons of CO2 equivalent)'
 'Agricultural nitrous oxide emissions (% of total)'
 'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)'
 'Agricultural raw materials exports (% of merchandise exports)'
 'Agricultural raw materials imports (% of merchandise imports)'
 'Agriculture, forestry, and fishing, value added (% of GDP)'
 'Agriculture, forestry, and fishing, value added (annual % growth)'
 'Agriculture, forestry, and fishing, value added (constant 2015 US$)'
 'Agriculture, forestry, and fishing, value added (constant LCU)'
 'Agriculture, forestry, and fishing, value added (current LCU)'
 'Agriculture, forestry, and fishing, value added (current US$)'
 'Agriculture, forestry, and fishing, value added per worker (constant 2015 US$)'
 'Air transport, freight (million ton-km)'
 'Air transport, passengers carried'
 'Air transport, registered carrier departures worldwide'
 'Alternative and nuclear energy (% of total energy use)'
 'Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)'
 'Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)'
 'Annual freshwater withdrawals, industry (% of total freshwater withdrawal)'
 'Annual freshwater withdrawals, total (% of internal resources)'
 'Annual freshwater withdrawals, total (billion cubic meters)'
 'Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)'
 'Annualized average growth rate in per capita real survey mean consumption or income, total population (%)'
 'Antiretroviral therapy coverage (% of people living with HIV)'
 'Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)'
 'Aquaculture production (metric tons)' 'Arable land (% of land area)'
 'Arable land (hectares per person)' 'Arable land (hectares)'
 'ARI treatment (% of children under 5 taken to a health provider)'
 'Armed forces personnel (% of total labor force)'
 'Armed forces personnel, total'
 'Arms exports (SIPRI trend indicator values)'
 'Arms imports (SIPRI trend indicator values)'
 'Automated teller machines (ATMs) (per 100,000 adults)'
 'Average precipitation in depth (mm per year)'
 'Average time to clear exports through customs (days)'
 'Average transaction cost of sending remittances from a specific country (%)'
 'Average transaction cost of sending remittances to a specific country (%)'
 'Average working hours of children, study and work, ages 7-14 (hours per week)'
 'Average working hours of children, study and work, female, ages 7-14 (hours per week)'
 'Average working hours of children, study and work, male, ages 7-14 (hours per week)'
 'Average working hours of children, working only, ages 7-14 (hours per week)'
 'Average working hours of children, working only, female, ages 7-14 (hours per week)'
 'Average working hours of children, working only, male, ages 7-14 (hours per week)'
 'Bank capital to assets ratio (%)'
 'Bank liquid reserves to bank assets ratio (%)'
 'Bank nonperforming loans to total gross loans (%)'
 'Battle-related deaths (number of people)'
 'Benefit incidence of social insurance programs to poorest quintile (% of total social insurance benefits)'
 'Benefit incidence of social protection and labor programs to poorest quintile (% of total SPL benefits)'
 'Benefit incidence of social safety net programs to poorest quintile (% of total safety net benefits)'
 'Benefit incidence of unemployment benefits and ALMP to poorest quintile (% of total U/ALMP benefits)'
 'Binding coverage, all products (%)'
 'Binding coverage, manufactured products (%)'
 'Binding coverage, primary products (%)' 'Bird species, threatened'
 'Birth rate, crude (per 1,000 people)'
 'Births attended by skilled health staff (% of total)'
 'Borrowers from commercial banks (per 1,000 adults)'
 'Bound rate, simple mean, all products (%)'
 'Bound rate, simple mean, manufactured products (%)'
 'Bound rate, simple mean, primary products (%)'
 'Bribery incidence (% of firms experiencing at least one bribe payment request)'
 'Broad money (% of GDP)' 'Broad money (current LCU)'
 'Broad money growth (annual %)' 'Broad money to total reserves ratio'
 'Business extent of disclosure index (0=less disclosure to 10=more disclosure)'
 'Capture fisheries production (metric tons)'
 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)'
 'Cause of death, by injury (% of total)'
 'Cause of death, by non-communicable diseases (% of total)'
 'Central government debt, total (% of GDP)'
 'Central government debt, total (current LCU)'
 'Cereal production (metric tons)' 'Cereal yield (kg per hectare)'
 'Changes in inventories (constant LCU)'
 'Changes in inventories (current LCU)'
 'Changes in inventories (current US$)'
 'Charges for the use of intellectual property, payments (BoP, current US$)'
 'Charges for the use of intellectual property, receipts (BoP, current US$)'
 'Chemicals (% of value added in manufacturing)'
 'Child employment in agriculture (% of economically active children ages 7-14)'
 'Child employment in agriculture, female (% of female economically active children ages 7-14)'
 'Child employment in agriculture, male (% of male economically active children ages 7-14)'
 'Child employment in manufacturing (% of economically active children ages 7-14)'
 'Child employment in manufacturing, female (% of female economically active children ages 7-14)'
 'Child employment in manufacturing, male (% of male economically active children ages 7-14)'
 'Child employment in services (% of economically active children ages 7-14)'
 'Child employment in services, female (% of female economically active children ages 7-14)'
 'Child employment in services, male (% of male economically active children ages 7-14)'
 'Children (0-14) living with HIV'
 'Children (ages 0-14) newly infected with HIV'
 'Children in employment, female (% of female children ages 7-14)'
 'Children in employment, male (% of male children ages 7-14)'
 'Children in employment, self-employed (% of children in employment, ages 7-14)'
 'Children in employment, self-employed, female (% of female children in employment, ages 7-14)'
 'Children in employment, self-employed, male (% of male children in employment, ages 7-14)'
 'Children in employment, study and work (% of children in employment, ages 7-14)'
 'Children in employment, study and work, female (% of female children in employment, ages 7-14)'
 'Children in employment, study and work, male (% of male children in employment, ages 7-14)'
 'Children in employment, total (% of children ages 7-14)'
 'Children in employment, unpaid family workers (% of children in employment, ages 7-14)'
 'Children in employment, unpaid family workers, female (% of female children in employment, ages 7-14)'
 'Children in employment, unpaid family workers, male (% of male children in employment, ages 7-14)'
 'Children in employment, wage workers (% of children in employment, ages 7-14)'
 'Children in employment, wage workers, female (% of female children in employment, ages 7-14)'
 'Children in employment, wage workers, male (% of male children in employment, ages 7-14)'
 'Children in employment, work only (% of children in employment, ages 7-14)'
 'Children in employment, work only, female (% of female children in employment, ages 7-14)'
 'Children in employment, work only, male (% of male children in employment, ages 7-14)'
 'Children out of school (% of primary school age)'
 'Children out of school, female (% of female primary school age)'
 'Children out of school, male (% of male primary school age)'
 'Children out of school, primary'
 'Children out of school, primary, female'
 'Children out of school, primary, male'
 'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)'
 'Claims on central government (annual growth as % of broad money)'
 'Claims on central government, etc. (% GDP)'
 'Claims on other sectors of the domestic economy (% of GDP)'
 'Claims on other sectors of the domestic economy (annual growth as % of broad money)'
 'Claims on private sector (annual growth as % of broad money)'
 'CO2 emissions (kg per 2015 US$ of GDP)'
 'CO2 emissions (kg per 2017 PPP $ of GDP)'
 'CO2 emissions (kg per PPP $ of GDP)' 'CO2 emissions (kt)'
 'CO2 emissions (metric tons per capita)'
 'CO2 emissions from electricity and heat production, total (% of total fuel combustion)'
 'CO2 emissions from gaseous fuel consumption (% of total)'
 'CO2 emissions from gaseous fuel consumption (kt)'
 'CO2 emissions from liquid fuel consumption (% of total)'
 'CO2 emissions from liquid fuel consumption (kt)'
 'CO2 emissions from manufacturing industries and construction (% of total fuel combustion)'
 'CO2 emissions from other sectors, excluding residential buildings and commercial and public services (% of total fuel combustion)'
 'CO2 emissions from residential buildings and commercial and public services (% of total fuel combustion)'
 'CO2 emissions from solid fuel consumption (% of total)'
 'CO2 emissions from solid fuel consumption (kt)'
 'CO2 emissions from transport (% of total fuel combustion)'
 'CO2 intensity (kg per kg of oil equivalent energy use)'
 'Coal rents (% of GDP)'
 'Combustible renewables and waste (% of total energy)'
 'Commercial bank branches (per 100,000 adults)'
 'Commercial banks and other lending (PPG + PNG) (NFL, current US$)'
 'Commercial service exports (current US$)'
 'Commercial service imports (current US$)'
 'Communications, computer, etc. (% of service exports, BoP)'
 'Communications, computer, etc. (% of service imports, BoP)'
 'Community health workers (per 1,000 people)'
 'Compensation of employees (% of expense)'
 'Compensation of employees (current LCU)'
 'Completeness of birth registration (%)'
 'Completeness of birth registration, female (%)'
 'Completeness of birth registration, male (%)'
 'Completeness of birth registration, rural (%)'
 'Completeness of birth registration, urban (%)'
 'Completeness of death registration with cause-of-death information (%)'
 'Compulsory education, duration (years)'
 'Computer, communications and other services (% of commercial service exports)'
 'Computer, communications and other services (% of commercial service imports)'
 'Condom use, population ages 15-24, female (% of females ages 15-24)'
 'Condom use, population ages 15-24, male (% of males ages 15-24)'
 'Consumer price index (2010 = 100)'
 'Consumption of iodized salt (% of households)'
 'Container port traffic (TEU: 20 foot equivalent units)'
 'Contraceptive prevalence, any method (% of married women ages 15-49)'
 'Contraceptive prevalence, any modern method (% of married women ages 15-49)'
 'Contributing family workers, female (% of female employment) (modeled ILO estimate)'
 'Contributing family workers, male (% of male employment) (modeled ILO estimate)'
 'Contributing family workers, total (% of total employment) (modeled ILO estimate)'
 'Control of Corruption: Estimate'
 'Control of Corruption: Number of Sources'
 'Control of Corruption: Percentile Rank'
 'Control of Corruption: Percentile Rank, Lower Bound of 90% Confidence Interval'
 'Control of Corruption: Percentile Rank, Upper Bound of 90% Confidence Interval'
 'Control of Corruption: Standard Error'
 'Cost of business start-up procedures (% of GNI per capita)'
 'Cost of business start-up procedures, female (% of GNI per capita)'
 'Cost of business start-up procedures, male (% of GNI per capita)'
 'Cost to export, border compliance (US$)'
 'Cost to export, documentary compliance (US$)'
 'Cost to import, border compliance (US$)'
 'Cost to import, documentary compliance (US$)'
 'Coverage of social insurance programs (% of population)'
 'Coverage of social insurance programs in 2nd quintile (% of population)'
 'Coverage of social insurance programs in 3rd quintile (% of population)'
 'Coverage of social insurance programs in 4th quintile (% of population)'
 'Coverage of social insurance programs in poorest quintile (% of population)'
 'Coverage of social insurance programs in richest quintile (% of population)'
 'Coverage of social protection and labor programs (% of population)'
 'Coverage of social safety net programs (% of population)'
 'Coverage of social safety net programs in 2nd quintile (% of population)'
 'Coverage of social safety net programs in 3rd quintile (% of population)'
 'Coverage of social safety net programs in 4th quintile (% of population)'
 'Coverage of social safety net programs in poorest quintile (% of population)'
 'Coverage of social safety net programs in richest quintile (% of population)'
 'Coverage of unemployment benefits and ALMP (% of population)'
 'Coverage of unemployment benefits and ALMP in 2nd quintile (% of population)'
 'Coverage of unemployment benefits and ALMP in 3rd quintile (% of population)'
 'Coverage of unemployment benefits and ALMP in 4th quintile (% of population)'
 'Coverage of unemployment benefits and ALMP in poorest quintile (% of population)'
 'Coverage of unemployment benefits and ALMP in richest quintile (% of population)'
 'CPIA building human resources rating (1=low to 6=high)'
 'CPIA business regulatory environment rating (1=low to 6=high)'
 'CPIA debt policy rating (1=low to 6=high)'
 'CPIA economic management cluster average (1=low to 6=high)'
 'CPIA efficiency of revenue mobilization rating (1=low to 6=high)'
 'CPIA equity of public resource use rating (1=low to 6=high)'
 'CPIA financial sector rating (1=low to 6=high)'
 'CPIA fiscal policy rating (1=low to 6=high)'
 'CPIA gender equality rating (1=low to 6=high)'
 'CPIA macroeconomic management rating (1=low to 6=high)'
 'CPIA policies for social inclusion/equity cluster average (1=low to 6=high)'
 'CPIA policy and institutions for environmental sustainability rating (1=low to 6=high)'
 'CPIA property rights and rule-based governance rating (1=low to 6=high)'
 'CPIA public sector management and institutions cluster average (1=low to 6=high)'
 'CPIA quality of budgetary and financial management rating (1=low to 6=high)'
 'CPIA quality of public administration rating (1=low to 6=high)'
 'CPIA social protection rating (1=low to 6=high)'
 'CPIA structural policies cluster average (1=low to 6=high)'
 'CPIA trade rating (1=low to 6=high)'
 'CPIA transparency, accountability, and corruption in the public sector rating (1=low to 6=high)'
 'Crop production index (2014-2016 = 100)'
 'Current account balance (% of GDP)'
 'Current account balance (BoP, current US$)'
 'Current education expenditure, primary (% of total expenditure in primary public institutions)'
 'Current education expenditure, secondary (% of total expenditure in secondary public institutions)'
 'Current education expenditure, tertiary (% of total expenditure in tertiary public institutions)'
 'Current education expenditure, total (% of total expenditure in public institutions)'
 'Current health expenditure (% of GDP)'
 'Current health expenditure per capita (current US$)'
 'Current health expenditure per capita, PPP (current international $)'
 'Customs and other import duties (% of tax revenue)'
 'Customs and other import duties (current LCU)'
 'Death rate, crude (per 1,000 people)'

In [17]:
# Adjusted savings: net forest depletion (current US$)
# Adjusted savings: mineral depletion (current US$)
# Adjusted savings: energy depletion (current US$)
# Adjusted savings: natural resources depletion (% of GNI)
# Adjusted savings: net national savings (current US$)
# Adjusted net national income (current US$)
# Adjusted net national income (annual % growth)
# Adjusted net national income per capita (current US$)
# Adjusted net national income per capita (annual % growth)
# Adjusted net savings, including particulate emission damage (current US$)
# Adjusted net savings, excluding particulate emission damage (current US$)

In [19]:
df_adj_netNatIncomePerCapita = df.loc[df['Indicator Name'] == "Adjusted net national income per capita (current US$)"]

In [20]:
df_adj_netNatIncomePerCapita.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
27,Africa Eastern and Southern,AFE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1296.804936,1310.864153,1228.102810,1152.953839,1259.544613,1264.541984,1234.247468,1097.744851,NaN,NaN
1504,Africa Western and Central,AFW,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1632.178624,1718.121017,1564.745629,1389.653342,1303.571811,1347.982442,1418.794409,1384.662115,NaN,NaN
2981,Arab World,ARB,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5731.746622,5759.499854,5108.260831,4980.008234,4920.930522,5223.738966,5246.297084,4722.985175,NaN,NaN
4458,Caribbean small states,CSS,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8064.482771,8434.010503,8571.967066,7919.162903,8147.649104,8343.680920,8589.465927,7312.511304,NaN,NaN
5935,Central Europe and the Baltics,CEB,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,11052.519856,11429.731472,10094.730964,10340.681664,11549.951035,13012.824321,13373.382950,13255.673927,NaN,NaN

In [21]:
df_adj_netNatIncomePerCapita.describe

<bound method NDFrame.describe of                           Country Name Country Code  \
27         Africa Eastern and Southern          AFE
1504        Africa Western and Central          AFW
2981                        Arab World          ARB
4458            Caribbean small states          CSS
5935    Central Europe and the Baltics          CEB
...                                ...          ...
385524           Virgin Islands (U.S.)          VIR
387001              West Bank and Gaza          PSE
388478                     Yemen, Rep.          YEM
389955                          Zambia          ZMB
391432                        Zimbabwe          ZWE

                                           Indicator Name     Indicator Code  \
27      Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD
1504    Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD
2981    Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD
4458    Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD
5935    Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD
...                                                   ...                ...
385524  Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD
387001  Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD
388478  Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD
389955  Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD
391432  Adjusted net national income per capita (curre...  NY.ADJ.NNTY.PC.CD

        1960  1961  1962  1963  1964  1965  ...          2013          2014  \
27       NaN   NaN   NaN   NaN   NaN   NaN  ...   1296.804936   1310.864153
1504     NaN   NaN   NaN   NaN   NaN   NaN  ...   1632.178624   1718.121017
2981     NaN   NaN   NaN   NaN   NaN   NaN  ...   5731.746622   5759.499854
4458     NaN   NaN   NaN   NaN   NaN   NaN  ...   8064.482771   8434.010503
5935     NaN   NaN   NaN   NaN   NaN   NaN  ...  11052.519856  11429.731472
...      ...   ...   ...   ...   ...   ...  ...           ...           ...
385524   NaN   NaN   NaN   NaN   NaN   NaN  ...           NaN           NaN
387001   NaN   NaN   NaN   NaN   NaN   NaN  ...           NaN           NaN
388478   NaN   NaN   NaN   NaN   NaN   NaN  ...   1274.731964   1323.300430
389955   NaN   NaN   NaN   NaN   NaN   NaN  ...   1413.864528   1379.444002
391432   NaN   NaN   NaN   NaN   NaN   NaN  ...   1227.332563   1207.234855

                2015          2016          2017          2018          2019  \
27       1228.102810   1152.953839   1259.544613   1264.541984   1234.247468
1504     1564.745629   1389.653342   1303.571811   1347.982442   1418.794409
2981     5108.260831   4980.008234   4920.930522   5223.738966   5246.297084
4458     8571.967066   7919.162903   8147.649104   8343.680920   8589.465927
5935    10094.730964  10340.681664  11549.951035  13012.824321  13373.382950
...              ...           ...           ...           ...           ...
385524           NaN           NaN           NaN           NaN           NaN
387001           NaN           NaN           NaN           NaN           NaN
388478   1366.083303   1016.850557    849.196530    666.413013           NaN
389955   1054.613559    992.835792   1144.782042   1145.844603    990.129619
391432   1220.263319   1221.332601   1013.621411   1019.960476   1054.601646

                2020  2021  2022
27       1097.744851   NaN   NaN
1504     1384.662115   NaN   NaN
2981     4722.985175   NaN   NaN
4458     7312.511304   NaN   NaN
5935    13255.673927   NaN   NaN
...              ...   ...   ...
385524           NaN   NaN   NaN
387001           NaN   NaN   NaN
388478           NaN   NaN   NaN
389955    733.301291   NaN   NaN
391432    934.384341   NaN   NaN

[266 rows x 67 columns]>

In [22]:
df_pivot = pd.melt(df_adj_netNatIncomePerCapita,id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], value_vars=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],var_name='Year', value_name='indicator')

In [24]:
df_pivot.tail(100)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
16658,"Macao SAR, China",MAC,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN
16659,Madagascar,MDG,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN
16660,Malawi,MWI,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN
16661,Malaysia,MYS,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN
16662,Maldives,MDV,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN
...,...,...,...,...,...,...
16753,Virgin Islands (U.S.),VIR,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN
16754,West Bank and Gaza,PSE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN
16755,"Yemen, Rep.",YEM,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN
16756,Zambia,ZMB,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN
16757,Zimbabwe,ZWE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2022,NaN

In [25]:
df_pivot.dropna(subset=['indicator'],inplace=True)

In [26]:
df_pivot

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
2661,Africa Western and Central,AFW,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,1970,192.349023
2665,Early-demographic dividend,EAR,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,1970,197.795431
2666,East Asia & Pacific,EAS,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,1970,272.504153
2667,East Asia & Pacific (excluding high income),EAP,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,1970,103.042967
2668,East Asia & Pacific (IDA & IBRD countries),TEA,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,1970,104.315710
...,...,...,...,...,...,...
16217,Uzbekistan,UZB,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2020,1375.453045
16218,Vanuatu,VUT,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2020,2831.753550
16220,Viet Nam,VNM,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2020,2251.858478
16224,Zambia,ZMB,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2020,733.301291
16225,Zimbabwe,ZWE,Adjusted net national income per capita (curre...,NY.ADJ.NNTY.PC.CD,2020,934.384341

In [27]:
df_pivot.to_csv("Adjusted net national income per capita A4.csv")

In [28]:
df_GDPperCapita = df.loc[df['Indicator Name'] == "GDP per capita (current US$)"]

In [29]:
df_GDPperCapita

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
480,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,161.638982,161.111657,170.538537,198.038919,178.019217,196.818756,...,1736.222507,1724.534381,1545.559084,1436.094404,1613.668488,1550.111762,1499.954437,1353.927527,1539.165543,1622.391720
1957,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,107.423775,112.503866,118.197351,122.774120,131.163760,137.809818,...,2153.766138,2247.857492,1880.750778,1646.972399,1588.581005,1732.816544,1810.538006,1686.997899,1765.965307,1790.348800
3434,Arab World,ARB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7348.849550,7302.250350,6283.256026,6113.397738,6224.522970,6573.816970,6498.529037,5639.398735,6414.725618,7655.848402
4911,Caribbean small states,CSS,GDP per capita (current US$),NY.GDP.PCAP.CD,446.724344,475.196775,493.291450,515.430227,546.452701,578.953997,...,10542.075211,10711.778657,10447.679948,9769.469641,10061.086612,10339.100779,10409.716383,8864.604370,10114.146841,12382.375376
6388,Central Europe and the Baltics,CEB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,13665.726598,14141.100616,12525.632700,12782.222240,14222.454291,16077.023947,16349.005358,16298.267059,18790.418160,19337.889031
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385977,Virgin Islands (U.S.),VIR,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,34597.976694,33045.364380,34007.352941,35324.974887,35365.069304,36653.863048,38596.030712,39552.168595,NaN,NaN
387454,West Bank and Gaza,PSE,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3315.297539,3352.112595,3272.154324,3527.613824,3620.360487,3562.330943,3656.858271,3233.568638,3678.635657,3789.327966
388931,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1497.747941,1557.601406,1488.416267,1069.816997,893.716573,701.714878,693.816484,583.875663,603.707959,676.928385
390408,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,228.567399,216.274674,208.562685,209.453362,236.941713,296.022427,...,1840.320553,1724.576220,1307.909649,1249.923143,1495.752138,1475.199836,1268.120941,956.831747,1137.344395,1487.907764
391885,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,276.643363,279.332656,275.966139,277.532515,282.376856,294.893605,...,1408.367810,1407.034291,1410.329173,1421.787791,1192.107012,2269.177012,1421.868596,1372.696674,1773.920411,1266.996031

In [30]:
df_pivot_GDP = pd.melt(df_GDPperCapita,id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], value_vars=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],var_name='Year', value_name='GDP_per_captia')

In [31]:
df_pivot_GDP

,Country Name,Country Code,Indicator Name,Indicator Code,Year,GDP_per_captia
0,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,161.638982
1,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,107.423775
2,Arab World,ARB,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,NaN
3,Caribbean small states,CSS,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,446.724344
4,Central Europe and the Baltics,CEB,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,NaN
...,...,...,...,...,...,...
16753,Virgin Islands (U.S.),VIR,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,NaN
16754,West Bank and Gaza,PSE,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,3789.327966
16755,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,676.928385
16756,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,1487.907764
16757,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,1266.996031

In [32]:
df_pivot_GDP.dropna(subset=['GDP_per_captia'],inplace=True)

In [33]:
df_pivot_GDP

,Country Name,Country Code,Indicator Name,Indicator Code,Year,GDP_per_captia
0,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,161.638982
1,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,107.423775
3,Caribbean small states,CSS,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,446.724344
5,Early-demographic dividend,EAR,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,153.477606
6,East Asia & Pacific,EAS,GDP per capita (current US$),NY.GDP.PCAP.CD,1960,148.212965
...,...,...,...,...,...,...
16752,Viet Nam,VNM,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,4163.514300
16754,West Bank and Gaza,PSE,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,3789.327966
16755,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,676.928385
16756,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,1487.907764
16757,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,2022,1266.996031

In [34]:
df_pivot_GDP.to_csv("GDP per capita A4.csv")

In [37]:
#EG.ELC.ACCS.ZS #access to electricity %ge population
#EN.ATM.CO2E.PC #CO2 emissions (metric tons per capita

In [43]:
df_elec_co2 = df_adj_netNatIncomePerCapita = df.loc[(df['Indicator Code'] == "EG.ELC.ACCS.ZS") | (df['Indicator Code'] == "EN.ATM.CO2E.PC")]

In [44]:
df_elec_co2

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.695183,31.859257,33.903515,38.851444,40.197332,43.028332,44.389773,46.268621,48.103609,NaN
193,Africa Eastern and Southern,AFE,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,1.001154,1.013758,0.960430,0.941337,0.933874,0.921453,0.915294,0.795420,NaN,NaN
1480,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,47.051990,47.647405,46.758948,50.903108,48.787640,51.212863,51.160817,51.734388,54.224187,NaN
1670,Africa Western and Central,AFW,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,0.481623,0.493505,0.475577,0.479775,0.465166,0.475817,0.490837,0.463150,NaN,NaN
2957,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,89.340705,88.832276,89.053852,89.539016,90.662754,89.176939,90.352802,90.635050,90.845661,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388644,"Yemen, Rep.",YEM,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,1.031167,0.988347,0.475240,0.342802,0.322370,0.368614,0.354864,0.308515,NaN,NaN
389931,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,30.052702,27.900000,31.100000,35.377220,40.300000,40.229340,43.000000,44.604069,46.685116,NaN
390121,Zambia,ZMB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,0.278215,0.297755,0.305055,0.316995,0.393726,0.440527,0.414336,0.401903,NaN,NaN
391408,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.644161,32.300000,33.700000,42.465588,43.979065,45.400288,46.682095,52.747667,48.979927,NaN
391598,Zimbabwe,ZWE,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,0.901248,0.866838,0.846962,0.723062,0.663069,0.735435,0.663338,0.530484,NaN,NaN

In [48]:
df_elec_co2_pivot = pd.melt(df_elec_co2,id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], value_vars=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],var_name='Year', value_name='indicator')
df_elec_co2_pivot.dropna(subset=['indicator'],inplace=True)

In [56]:
df_elec_co2_pivot["Year"] = df_elec_co2_pivot["Year"].astype(int)

In [63]:
#only need from 2000 to 2020
df_elec_co2_pivot["Year"] = df_elec_co2_pivot["Year"].astype(int)
df_elec_co2_pivot_20_22 = df_elec_co2_pivot.loc[df_elec_co2_pivot['Year'] >= 2000]
df_elec_co2_pivot_20_2020 = df_elec_co2_pivot_20_22.loc[df_elec_co2_pivot_20_22['Year'] <= 2020]

In [66]:
df_elec_co2_pivot_20_2020

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
21280,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000,19.957302
21281,Africa Eastern and Southern,AFE,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2000,0.891352
21282,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000,34.137971
21283,Africa Western and Central,AFW,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2000,0.521689
21284,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000,81.108851
...,...,...,...,...,...,...
32447,"Yemen, Rep.",YEM,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2020,0.308515
32448,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020,44.604069
32449,Zambia,ZMB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2020,0.401903
32450,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020,52.747667
32451,Zimbabwe,ZWE,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2020,0.530484

In [65]:
df_elec_co2_pivot_20_2020.to_csv("electricity and CO2 data 2000-2020.csv")

In [67]:
df_elec = df_elec_co2_pivot_20_2020.loc[df_elec_co2_pivot_20_2020["Indicator Code"]=="EG.ELC.ACCS.ZS"]

In [68]:
df_co2 = df_elec_co2_pivot_20_2020.loc[df_elec_co2_pivot_20_2020["Indicator Code"]=="EN.ATM.CO2E.PC"]

In [69]:
df_elec

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
21280,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000,19.957302
21282,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000,34.137971
21284,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000,81.108851
21286,Caribbean small states,CSS,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000,86.858925
21288,Central Europe and the Baltics,CEB,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000,97.926068
...,...,...,...,...,...,...
32442,Virgin Islands (U.S.),VIR,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020,100.000000
32444,West Bank and Gaza,PSE,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020,100.000000
32446,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020,73.853462
32448,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020,44.604069
32450,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020,52.747667

In [70]:
df_co2

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
21281,Africa Eastern and Southern,AFE,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2000,0.891352
21283,Africa Western and Central,AFW,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2000,0.521689
21285,Arab World,ARB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2000,3.253567
21287,Caribbean small states,CSS,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2000,4.327653
21289,Central Europe and the Baltics,CEB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2000,6.552228
...,...,...,...,...,...,...
32439,"Venezuela, RB",VEN,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2020,2.545028
32441,Viet Nam,VNM,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2020,3.676440
32447,"Yemen, Rep.",YEM,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2020,0.308515
32449,Zambia,ZMB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2020,0.401903
32451,Zimbabwe,ZWE,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2020,0.530484

In [84]:
result = pd.concat([df_elec, df_co2], axis=1).reindex(df_elec.index)

In [85]:
result

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
21280,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000.0,19.957302,NaN,NaN,NaN,NaN,NaN,NaN
21282,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000.0,34.137971,NaN,NaN,NaN,NaN,NaN,NaN
21284,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000.0,81.108851,NaN,NaN,NaN,NaN,NaN,NaN
21286,Caribbean small states,CSS,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000.0,86.858925,NaN,NaN,NaN,NaN,NaN,NaN
21288,Central Europe and the Baltics,CEB,Access to electricity (% of population),EG.ELC.ACCS.ZS,2000.0,97.926068,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
32442,Virgin Islands (U.S.),VIR,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020.0,100.000000,NaN,NaN,NaN,NaN,NaN,NaN
32444,West Bank and Gaza,PSE,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020.0,100.000000,NaN,NaN,NaN,NaN,NaN,NaN
32446,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020.0,73.853462,NaN,NaN,NaN,NaN,NaN,NaN
32448,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020.0,44.604069,NaN,NaN,NaN,NaN,NaN,NaN
32450,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,2020.0,52.747667,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
df_co2.to_csv("CO2 2000-2020.csv")
df_elec.to_csv("elec 2000-2022.csv")

In [89]:
df_greenhouse = df.loc[(df['Indicator Code'] == "EN.ATM.GHGT.KT.CE")]

In [91]:
df_greenhouse_pivot = pd.melt(df_greenhouse,id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], value_vars=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],var_name='Year', value_name='indicator')
df_greenhouse_pivot.dropna(subset=['indicator'],inplace=True)

In [92]:
df_greenhouse_pivot

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
7980,Africa Eastern and Southern,AFE,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,1990,7.982465e+05
7981,Africa Western and Central,AFW,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,1990,4.153427e+05
7982,Arab World,ARB,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,1990,1.107754e+06
7983,Caribbean small states,CSS,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,1990,5.020461e+04
7984,Central Europe and the Baltics,CEB,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,1990,1.241992e+06
...,...,...,...,...,...,...
16219,"Venezuela, RB",VEN,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,2020,1.942597e+05
16220,Viet Nam,VNM,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,2020,4.705781e+05
16223,"Yemen, Rep.",YEM,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,2020,2.439115e+04
16224,Zambia,ZMB,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,2020,3.610782e+04
16225,Zimbabwe,ZWE,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE,2020,2.598813e+04

In [93]:
df_greenhouse_pivot["Year"] = df_greenhouse_pivot["Year"].astype(int)
df_greenhouse_pivot_20_22 = df_greenhouse_pivot.loc[df_greenhouse_pivot['Year'] >= 2000]
df_greenhouse_pivot_20_2020 = df_greenhouse_pivot_20_22.loc[df_greenhouse_pivot_20_22['Year'] <= 2020]

In [95]:
df_greenhouse_pivot_20_2020.to_csv("greenhouse 2020-2022.csv")

In [104]:
df2 = pd.read_csv("per capita greenhouse emission.csv")

In [105]:
df2['Indicator Name'] = 'Greenhouse emission per capita'

In [106]:
df2

,Country Name,Country Code,2000,2001,2002,2003,2004,2005,2006,2007,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Indicator Name
0,Afghanistan,AFG,726.876035090244,640.20495431069,726.438455321687,704.832902261987,661.132258995682,681.480914224955,678.544366956906,703.340740626069,...,1015.1672718728,964.779126887622,952.610825031383,936.76432508523,891.119042855934,890.782989442819,888.07160256947,866.75148034132,798.492808597301,Greenhouse emission per capita
1,Albania,ALB,2642.89615532658,2654.37179401295,2870.99793543777,3015.94518024645,3054.66061258585,2994.18259285197,2980.9993443712,3027.17393065427,...,3127.34180652951,3211.74240749517,3370.87217940233,3266.13515659198,3195.90411567605,3453.77505283705,3374.08228404089,3222.05586802004,2926.26384983838,Greenhouse emission per capita
2,Algeria,DZA,5257.5398832694,5101.33430402918,5236.1758829239,5581.83239875189,5622.40847222467,5768.26022273475,5914.31922699153,5913.8890037311,...,6302.9597942468,6305.63980446006,6510.07675198931,6619.23161718461,6518.42280024043,6457.24560345927,6539.50094267401,6537.83438653426,6137.91608128443,Greenhouse emission per capita
3,American Samoa,ASM,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,Greenhouse emission per capita
4,Andorra,AND,8897.80123152337,8740.04727219109,8535.19518976979,8294.28987781942,8361.64090832283,8300.2299877233,7951.47212076638,8125.57480042984,...,8436.57868277639,8250.54784424174,8026.45779869033,8073.32840855239,8076.2429556107,7924.811517261,8230.75936171064,7934.13405289286,7433.38016731017,Greenhouse emission per capita
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Sub-Saharan Africa,SSF,2279.28474043166,2279.21497783231,2266.34575638146,2315.45945627532,2322.87552090003,2326.06057002895,2254.31653155524,2264.36440983334,...,2174.13036005143,2167.07586442802,2157.80243170507,2106.99066719519,2094.30334980962,2063.20061732145,2044.93903133305,2044.56082662685,1961.77488720182,Greenhouse emission per capita
262,Sub-Saharan Africa (excluding high income),SSA,2278.9886559301,2278.88410693301,2265.98672841713,2315.1230816356,2322.49207996111,2325.68825770006,2253.93847549076,2263.97472679853,...,2173.74863426131,2166.71386344113,2157.40106350131,2106.55138960591,2093.80751605461,2062.70671260316,2044.42336871747,2044.0607912724,1961.27375834023,Greenhouse emission per capita
263,Sub-Saharan Africa (IDA & IBRD countries),TSS,2279.28474043166,2279.21497783231,2266.34575638146,2315.45945627532,2322.87552090003,2326.06057002895,2254.31653155524,2264.36440983334,...,2174.13036005143,2167.07586442802,2157.80243170508,2106.99066719519,2094.30334980962,2063.20061732145,2044.93903133305,2044.56082662685,1961.77488720182,Greenhouse emission per capita
264,Upper middle income,UMC,4776.88558619747,4856.68346782278,4981.66984814013,5316.22546739196,5672.03187305415,5992.10550761405,6294.90498815197,6567.17955485982,...,7663.79225888998,7786.50476384477,7767.56088581881,7642.97649296915,7586.58539250867,7695.52038280679,7886.48964296616,7971.2406033894,7875.38026045362,Greenhouse emission per capita
265,World,WLD,5567.4689811664,5555.97695666641,5551.36042084995,5683.66459193315,5839.9220944933,5952.30596751979,6047.96489890852,6168.91673477836,...,6333.46982585206,6351.85403296095,6318.14101069282,6230.0965869915,6178.20487814209,6206.62980313837,6273.97731287444,6210.9764492468,5897.08925867004,Greenhouse emission per capita

In [107]:
df_green_per_capita = pd.melt(df2,id_vars=['Country Name', 'Country Code', 'Indicator Name'], value_vars=['2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020'],var_name='Year', value_name='indicator')

In [110]:
df_green_per_capita.to_csv("greenhouse per capita12.csv")

In [108]:
df_green_per_capita

,Country Name,Country Code,Indicator Name,Year,indicator
0,Afghanistan,AFG,Greenhouse emission per capita,2000,726.876035090244
1,Albania,ALB,Greenhouse emission per capita,2000,2642.89615532658
2,Algeria,DZA,Greenhouse emission per capita,2000,5257.5398832694
3,American Samoa,ASM,Greenhouse emission per capita,2000,..
4,Andorra,AND,Greenhouse emission per capita,2000,8897.80123152337
...,...,...,...,...,...
5581,Sub-Saharan Africa,SSF,Greenhouse emission per capita,2020,1961.77488720182
5582,Sub-Saharan Africa (excluding high income),SSA,Greenhouse emission per capita,2020,1961.27375834023
5583,Sub-Saharan Africa (IDA & IBRD countries),TSS,Greenhouse emission per capita,2020,1961.77488720182
5584,Upper middle income,UMC,Greenhouse emission per capita,2020,7875.38026045362
5585,World,WLD,Greenhouse emission per capita,2020,5897.08925867004

In [111]:
#pick required indicator/s
df_new = df.loc[df['Indicator Code'] == "SP.POP.TOTL"]
#pivot to get years
df_pivot_1 = pd.melt(df_new,id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], value_vars=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],var_name='Year', value_name='indicator')
#remove null values
df_pivot_1.dropna(subset=['indicator'],inplace=True)
#filter for required time
df_pivot_1["Year"] = df_pivot_1["Year"].astype(int)
df_pivot_1_20_22 = df_pivot_1.loc[df_pivot_1['Year'] >= 2000]
df_pivot_1_20_2020 = df_pivot_1_20_22.loc[df_pivot_1_20_22['Year'] <= 2020]
#check once
df_pivot_1_20_2020

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
10640,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,2000,401600588.0
10641,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,2000,269611898.0
10642,Arab World,ARB,"Population, total",SP.POP.TOTL,2000,287065982.0
10643,Caribbean small states,CSS,"Population, total",SP.POP.TOTL,2000,6582141.0
10644,Central Europe and the Baltics,CEB,"Population, total",SP.POP.TOTL,2000,108447824.0
...,...,...,...,...,...,...
16221,Virgin Islands (U.S.),VIR,"Population, total",SP.POP.TOTL,2020,106290.0
16222,West Bank and Gaza,PSE,"Population, total",SP.POP.TOTL,2020,4803269.0
16223,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,2020,32284046.0
16224,Zambia,ZMB,"Population, total",SP.POP.TOTL,2020,18927715.0
16225,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,2020,15669666.0

In [113]:
#extract as CSV
df_pivot_1_20_2020.to_csv("population.csv")

In [114]:
#EG.ELC.ACCS.RU.ZS  Access to electricity, rural (% of rural population)
#EG.ELC.ACCS.UR.ZS Access to electricity, urban (% of urban population)

In [115]:
#pick required indicator/s
df_new = df.loc[df['Indicator Code'] == "EG.ELC.ACCS.RU.ZS"]
#pivot to get years
df_pivot_1 = pd.melt(df_new,id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], value_vars=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],var_name='Year', value_name='indicator')
#remove null values
df_pivot_1.dropna(subset=['indicator'],inplace=True)
#filter for required time
df_pivot_1["Year"] = df_pivot_1["Year"].astype(int)
df_pivot_1_20_22 = df_pivot_1.loc[df_pivot_1['Year'] >= 2000]
df_pivot_1_20_2020 = df_pivot_1_20_22.loc[df_pivot_1_20_22['Year'] <= 2020]
#check once
df_pivot_1_20_2020

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
10640,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2000,8.623497
10641,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2000,16.657281
10642,Arab World,ARB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2000,69.415057
10643,Caribbean small states,CSS,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2000,79.014899
10644,Central Europe and the Baltics,CEB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2000,96.974111
...,...,...,...,...,...,...
16221,Virgin Islands (U.S.),VIR,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2020,100.000000
16222,West Bank and Gaza,PSE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2020,100.000000
16223,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2020,62.109128
16224,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2020,13.971176
16225,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,2020,37.060248

In [116]:
df_pivot_1_20_2020.to_csv("rural_electricity.csv")

In [117]:
#pick required indicator/s
df_new = df.loc[df['Indicator Code'] == "EG.ELC.ACCS.UR.ZS"]
#pivot to get years
df_pivot_1 = pd.melt(df_new,id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], value_vars=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],var_name='Year', value_name='indicator')
#remove null values
df_pivot_1.dropna(subset=['indicator'],inplace=True)
#filter for required time
df_pivot_1["Year"] = df_pivot_1["Year"].astype(int)
df_pivot_1_20_22 = df_pivot_1.loc[df_pivot_1['Year'] >= 2000]
df_pivot_1_20_2020 = df_pivot_1_20_22.loc[df_pivot_1_20_22['Year'] <= 2020]
#check once
df_pivot_1_20_2020

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
10640,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2000,53.681658
10641,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2000,71.403127
10642,Arab World,ARB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2000,94.372089
10643,Caribbean small states,CSS,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2000,94.704586
10644,Central Europe and the Baltics,CEB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2000,98.424434
...,...,...,...,...,...,...
16221,Virgin Islands (U.S.),VIR,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2020,100.000000
16222,West Bank and Gaza,PSE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2020,100.000000
16223,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2020,93.090279
16224,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2020,82.610161
16225,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,2020,85.715476

In [118]:
df_pivot_1_20_2020.to_csv("urban_electricity.csv")

In [119]:
#Renewable Energy Consumption (% Of Total Final Energy Consumption)

In [127]:
#pick required indicator/s
df_new = df.loc[df['Indicator Code'] == "EG.FEC.RNEW.ZS"]
#pivot to get years
df_pivot_1 = pd.melt(df_new,id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], value_vars=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'],var_name='Year', value_name='indicator')
#remove null values
df_pivot_1.dropna(subset=['indicator'],inplace=True)
#filter for required time
df_pivot_1["Year"] = df_pivot_1["Year"].astype(int)
df_pivot_1_20_22 = df_pivot_1.loc[df_pivot_1['Year'] >= 2000]
df_pivot_1_20_2020 = df_pivot_1_20_22.loc[df_pivot_1_20_22['Year'] <= 2020]
#check once
df_pivot_1_20_2020

,Country Name,Country Code,Indicator Name,Indicator Code,Year,indicator
10640,Africa Eastern and Southern,AFE,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2000,65.449524
10641,Africa Western and Central,AFW,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2000,83.273305
10642,Arab World,ARB,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2000,6.672582
10643,Caribbean small states,CSS,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2000,10.470851
10644,Central Europe and the Baltics,CEB,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2000,9.941114
...,...,...,...,...,...,...
16221,Virgin Islands (U.S.),VIR,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2020,5.130000
16222,West Bank and Gaza,PSE,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2020,15.020000
16223,"Yemen, Rep.",YEM,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2020,3.530000
16224,Zambia,ZMB,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2020,81.840000
16225,Zimbabwe,ZWE,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS,2020,84.360000

In [128]:
df_pivot_1_20_2020.to_csv("renewable electricity output.csv")